# Generated by Django 4.2 on 2023-05-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=100)),
                ('pr_price', models.IntegerField(max_length=100)),
                ('category', models.CharField(choices=[('electronics', 'electronics'), ('food', 'food'), ('fashion', 'fashion'), ('home applianses', 'home applianses'), ('furniture', 'furniture'), ('grocery', 'grocery')], default='', max_length=100)),
                ('image', models.ImageField(upload_to='productImage')),
            ],
        ),
    ]
