# Generated by Django 4.2 on 2023-05-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pr_discription',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
